# Generated by Django 5.1.2 on 2024-11-05 02:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('professor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('seating', models.CharField(choices=[('FR', 'Front Right'), ('FM', 'Front Middle'), ('FL', 'Front Left'), ('BR', 'Back Right'), ('BM', 'Back Middle'), ('BL', 'Back Left'), ('NA', 'None')], default='NA', max_length=3)),
                ('total_calls', models.IntegerField(default=0)),
                ('absent_calls', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coldcall.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendance', models.BooleanField(default=True)),
                ('prepared', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=5)),
                ('student_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coldcall.student')),
            ],
        ),
    ]
