# Generated by Django 5.1.2 on 2024-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0002_class_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
