# Generated by Django 5.1.2 on 2025-01-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0003_class_end_date_class_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usc_id',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
