# Generated by Django 5.1.2 on 2025-02-07 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0004_student_usc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
