# Generated by Django 5.1.2 on 2025-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0005_student_email_alter_studentrating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usc_id',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
