# Generated by Django 5.1.2 on 2025-02-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0007_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usc_id',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
