# Generated by Django 5.1.2 on 2025-02-27 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0007_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
