# Generated by Django 5.1.2 on 2025-03-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0008_alter_studentrating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
    ]
