# Generated by Django 5.1.2 on 2025-03-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0009_student_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrating',
            name='class_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coldcall.class'),
        ),
    ]
