# Generated by Django 5.1.2 on 2025-03-28 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0010_studentrating_class_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coldcall.class')),
                ('student_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coldcall.student')),
            ],
        ),
    ]
