# Generated by Django 5.1.2 on 2025-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0011_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
