# Generated by Django 5.1.2 on 2025-04-05 01:04

import coldcall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0012_userdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=coldcall.models.hash_filename),
        ),
    ]
