# Generated by Django 5.1.2 on 2025-04-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0013_alter_userdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coldcall.class'),
        ),
    ]
