# Generated by Django 5.1.2 on 2025-04-19 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0014_alter_student_class_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('professor_key', 'class_name', 'start_date', 'end_date'), name='unique_class_name_per_professor'),
        ),
    ]
