# Generated by Django 5.1.2 on 2025-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0015_class_unique_class_name_per_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unprepared_calls',
            field=models.IntegerField(default=0),
        ),
    ]
