# Generated by Django 5.1.2 on 2025-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldcall', '0016_student_unprepared_calls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['dropped', 'last_name']},
        ),
        migrations.AddField(
            model_name='student',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
    ]
